apiVersion:  helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carriertessera
  namespace: carrier-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carriertessera
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_tessera
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    replicaCount: 1
    metadata:
      namespace: carrier-bes
      labels:
    images:
      alpineutils: ghcr.io/hyperledger/bevel-alpine-ext:latest
      tessera: quorumengineering/tessera:hashicorp-21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    tessera:
      name: carrier-tessera
      dbname: demodb
      dburl: "jdbc:mysql://carrier-tessera:3306/demodb"
      dbusername: demouser
      tls: "STRICT"
      url: "https://carrier.test.besu.evasquezapplaudo.ml:443"
      clienturl: "https://carrier-tessera:8888"
      othernodes:
        - url: https://carrier.test.besu.evasquezapplaudo.ml
        - url: https://manufacturer.test.besu.evasquezapplaudo.ml
        - url: https://store.test.besu.evasquezapplaudo.ml
        - url: https://warehouse.test.besu.evasquezapplaudo.ml
      trust: "TOFU"

      servicetype: ClusterIP
      ports:
        tm: 443
        db: 3306
        client: 8888
      mountPath: /etc/tessera/data
      ambassadorSecret: carrier-ambassador-certs
    vault:
      address: http://34.173.49.122:8200
      secretengine: secretsv2
      tmsecretpath: carrier-bes/crypto/carrier/tm
      secretprefix: data/carrier-bes/crypto/carrier
      serviceaccountname: vault-auth
      keyname: credentials
      type: hashicorp
      tm_keyname: tm
      tlsdir: tls
      role: vault-role
      authpath: besucarrier
    proxy:
      provider: "ambassador"
      external_url: carrier.test.besu.evasquezapplaudo.ml
      portTM: 443
    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi


    metrics:
      enabled: False
      port: 9545
