apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-gcp-storageclass
  namespace: carrier-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrier-gcp-storageclass
  interval: 1m
  chart:
    spec:
      chart: platforms/shared/charts/storage_class 
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
  values:
    metadata:
      name: carrier-gcp-storageclass
    cloud_provider: gcp
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowedTopologies:
      - matchLabelExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            values:
              - "eu-west-1a"
              - "eu-west-1b"
