apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychainvalidator1validator-node
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator1validator-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_validator
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://eab004e1b6f63dec2c02e64dd63f87cfb2f63992d535908aa59c3cd2afcc284be4b7442fa6703137bf1aa73d248c7c3ab19610c24cf4126bc4911101bce486bb@validator1.test.besu.blockchaincloudpoc.com:30303"
      - "enode://e9dc7a0d1c3859018dcc50a3f07f38d664b298ca6a8ca718979663bf2f8189213b7eb6b91d0761e8cc4739a67269ff2f58e04aafbcb284eb2317203b3a12b62f@validator2.test.besu.blockchaincloudpoc.com:30303"
      - "enode://2525babb4caa6174941712670edac6a3954f3c3d0c52042d087c72cda36a1e9bdf68523304dc0a353586dfd42cb2db682363c86269b9e472ac641dd54bf41f8f@validator3.test.besu.blockchaincloudpoc.com:30303"
      - "enode://67a8541e4f2d87daf72d39584426943222f68ced68d6cc3f94c33ef36b4ce93b8889c3c97da9bb678b53258a44f600104bcbb9136fd38f86464845d0d9c0723a@validator4.test.besu.blockchaincloudpoc.com:30303"
      - "enode://017799cbbd42b6902de4bb747ac048c6f0af28306a54187f1ef68e4bc6113019704d8559cd500bc691d3b89c468627082ecc84dbee36dc4e425ae0f65752da94@carrier.test.besu.blockchaincloudpoc.com:30303"
      - "enode://c6f3963b9fc4b790fab912055520df9603becffa8b1433046a8885625881f4f5f442293ecc4ede6a26e2fbd811a4dd5e5729b5473c70c8e4e2625b1945a8404d@manufacturer.test.besu.blockchaincloudpoc.com:30303"
      - "enode://27bbc1c28946f24c6a5b9f92b863f55f426117a2f6a5e5a7fb59b51787b373d429f65c78ea8466d26c088423bdaa3b3048f5741b33cd5eb95c8c9b7d993564a4@store.test.besu.blockchaincloudpoc.com:30303"
      - "enode://3efe67ec2a47cc824daedaded93e45cfdf8879bed6ee07c8b657cc8cee73f96c769a40baa1963a882fbd19446df65b2c5c5e812df5c60852c3c903e2634711a7@warehouse.test.besu.blockchaincloudpoc.com:30303"

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: test.besu.blockchaincloudpoc.com

    liveliness_check:
      enabled: false
    proxy:
      provider: none
      external_url: supplychain.supplychain-bes
      p2p: 30303
      rpc: 8545

    images:
      node: hyperledger/besu:22.10.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: validator1
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

      permissioning:
        enabled: False
      
    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi

    vault:
      address: http://34.173.49.122:8200
      secretengine: secretsv2
      secretprefix: data/supplychain-bes/crypto/validator1
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain
      type: hashicorp

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiYWxsb2MiOiB7CiAgICAiNzVhMzUwNWNkNTBDZmM0MThlNTk0NThkMEUyM2M4YmQ5ZjZCNTJhMCI6IHsKICAgICAgImJhbGFuY2UiOiAiOTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgImU2Njg1NTRjMjhlODE1MzVCODY3OWZmOWRlMTI4MjAzRmRlZGMyMTIiOiB7CiAgICAgICJiYWxhbmNlIjogIjkwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgfQogIH0sCiAgImV4dHJhRGF0YSI6ICIweGY4N2VhMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBmODU0OTQ2ZDVkOTA0Zjg1NjljNTMxZDM3YTc1MDQzNTQ4YzQ2Y2IwZTMyZTI4OTQ3N2QwZjFjNjlkNWYxZjc5OTViYzAwMDY3Y2Q5YzFiMmI3YzgyYTA4OTQ4YTNmMDhjODFiNWI0ZWM1OTU5NzA0MTVkMTEzNmJlZTk2ZTk1MzQzOTQ1MWJjMWRjNmIwYTdjMGE0MDU0ZTc0ODM1YmFhNmJkZjdjMzc1MTgzODA4NDAwMDAwMDAwYzAiCn0=


    metrics:
      enabled: False
      port: 9545    
