apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychainvalidator2validator-node
  namespace: supplychain-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainvalidator2validator-node
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-besu/charts/node_validator
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://641675b2296bdc535f8f87f92e2a845154f5a32d6ec2b1a1a1f9c86d6ac95877dd6f4582d74f6d06e40a252e95985170f8a0a566714a119d6e8c4c4e7b4e32c3@validator1.test.besu.blockchaincloudpoc.com:30303"
      - "enode://f1b916d6dc68746686dd00184574408788a24703bbd6cfce4ec6f29f639061f390e77237a7dcd3b7e8c3d5fceeb48fdc30d7b4b65559568afb7846cd410a62c2@validator2.test.besu.blockchaincloudpoc.com:30303"
      - "enode://ff833e8cdb87db88cd8a3b2a7e07eea72c4957df0ddc1433e18cd570ffee9c2ed442fa39b366d8f09b2c372715e66c1598c0749cbb422da20669b38baeeda446@validator3.test.besu.blockchaincloudpoc.com:30303"
      - "enode://73c94c9defdeb23e2e31a0b7d9858342247b02bee6dad73f9024b5c1bfe7affc5be77f92bfb93f09b9ae3432f4095da4aa0f57e690eae611948f2f491fa13d70@validator4.test.besu.blockchaincloudpoc.com:30303"
      - "enode://bb38e63fc0715e591badc9bbb0f214260021e99f550a1638ed7fb39ce04928dbdcc8c72a3cf03ea6c039d546c71764db009a8c1ad4a1b9c68ecb3fb906250ccc@carrier.test.besu.blockchaincloudpoc.com:30303"
      - "enode://a2893fb4caeb78dd4f4860d21d2fc1cee6192318a8b10b042614cdeebcb5ae37ebef590e08e18c3681eaf0677c346f5ea93dd329dda7ee7c5c698e8cb32cac0b@manufacturer.test.besu.blockchaincloudpoc.com:30303"
      - "enode://1aabfd50eedbaf7f01edac6ef9aa1f31dbddc9a3d4960f88b16af864982255f6ebbc4d62009b6a041c123c797fde46ae94777e92ff2951543a6512196d9b2a90@store.test.besu.blockchaincloudpoc.com:30303"
      - "enode://266cab61a422de1801f8c25cb79cf939847eea65582e791866f661146bbb0d64482b1a03fb783db4f3e099b88522672513c6a645f0efc8b2c92f429494ac93d5@warehouse.test.besu.blockchaincloudpoc.com:30303"

    metadata:
      namespace: supplychain-bes
      labels:

    ambassador:
      external_url_suffix: test.besu.blockchaincloudpoc.com

    liveliness_check:
      enabled: false
    proxy:
      provider: none
      external_url: supplychain.supplychain-bes
      p2p: 30303
      rpc: 8545

    images:
      node: hyperledger/besu:22.10.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      pullPolicy: IfNotPresent

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

      permissioning:
        enabled: False
      
    storage:
      storageclassname: gcpstorageclass
      storagesize: 1Gi

    vault:
      address: http://34.173.49.122:8200
      secretengine: secretsv2
      secretprefix: data/supplychain-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychain
      type: hashicorp

    genesis: 


    metrics:
      enabled: False
      port: 9545    
